// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_replace_rules_impl`, `ensure_regex_generation`, `get_or_compile_regex`, `get_or_load_rules`, `mark_chapter_failed`, `matches_scope`, `new`, `open_db`, `recompute_download_task_status`, `resolve_download_root`, `safe_download_file_name`, `storage_to_source_book_source`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReplaceRulesCache`

/// Smoke test — 验证桥接是否正常工作
Future<String> ping() => RustLib.instance.api.crateApiPing();

/// 初始化函数 - 在 Flutter 应用启动时调用
Future<String> initLegado({required String dbPath}) =>
    RustLib.instance.api.crateApiInitLegado(dbPath: dbPath);

/// 获取数据库版本
Future<int> getDbVersion({required String dbPath}) =>
    RustLib.instance.api.crateApiGetDbVersion(dbPath: dbPath);

/// 获取书架上的所有书籍，返回 JSON 数组。
///
/// 批次 8 (2026-05): 加 `sort_order: i32` 参数（0=Default/1=Name/2=Author/
/// 3=TimeAdd/4=DurTime/5=ChapterCount，越界回 Default）。语义详见
/// [`core_storage::book_dao::BookSort::from_i32`]。Flutter 端 `bookshelfSort`
/// 设置直接透传过来。
Future<String> getAllBooks(
        {required String dbPath, required int sortOrder}) =>
    RustLib.instance.api
        .crateApiGetAllBooks(dbPath: dbPath, sortOrder: sortOrder);

/// 搜索书架中的书籍，返回 JSON 数组
Future<String> searchBooksOffline(
        {required String dbPath, required String keyword}) =>
    RustLib.instance.api
        .crateApiSearchBooksOffline(dbPath: dbPath, keyword: keyword);

/// 保存一本书到书架（book_json 为 storage::Book 的 JSON）
Future<void> saveBook({required String dbPath, required String bookJson}) =>
    RustLib.instance.api.crateApiSaveBook(dbPath: dbPath, bookJson: bookJson);

/// 从书架删除一本书（同时级联删除该书籍的章节和阅读进度）
Future<void> deleteBook({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteBook(dbPath: dbPath, id: id);

/// 列出所有书架分组（按 sort_order 升序），返回 JSON 数组
Future<String> listBookGroups({required String dbPath}) =>
    RustLib.instance.api.crateApiListBookGroups(dbPath: dbPath);

/// 创建新分组，返回新分组的 JSON
Future<String> createBookGroup(
        {required String dbPath,
        required String name,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiCreateBookGroup(
        dbPath: dbPath, name: name, sortOrder: sortOrder);

/// 更新分组的 name + sort_order
Future<void> updateBookGroup(
        {required String dbPath,
        required PlatformInt64 id,
        required String name,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiUpdateBookGroup(
        dbPath: dbPath, id: id, name: name, sortOrder: sortOrder);

/// 删除分组（同事务把组内书的 group_id 重置为 0）
Future<void> deleteBookGroup(
        {required String dbPath, required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteBookGroup(dbPath: dbPath, id: id);

/// 列出某分组下的书籍。
///
/// `group_id` 语义：
/// - `-1` → 全部（等价 [`get_all_books`]）
/// - `0`  → 未分组
/// - `>= 1` → 具体某个分组
///
/// 批次 8 (2026-05): 加 `sort_order: i32`，与 [`get_all_books`] 同语义。
Future<String> listBooksByGroup(
        {required String dbPath,
        required PlatformInt64 groupId,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiListBooksByGroup(
        dbPath: dbPath, groupId: groupId, sortOrder: sortOrder);

/// 把一本书移动到指定分组（`group_id = 0` 表示移回"未分组"）
Future<void> setBookGroup(
        {required String dbPath,
        required String bookId,
        required PlatformInt64 groupId}) =>
    RustLib.instance.api
        .crateApiSetBookGroup(dbPath: dbPath, bookId: bookId, groupId: groupId);

/// 获取所有书源，返回 JSON 数组
Future<String> getAllSources({required String dbPath}) =>
    RustLib.instance.api.crateApiGetAllSources(dbPath: dbPath);

/// 获取所有已启用的书源，返回 JSON 数组
Future<String> getEnabledSources({required String dbPath}) =>
    RustLib.instance.api.crateApiGetEnabledSources(dbPath: dbPath);

/// 保存书源（source_json 为 storage::BookSource 的 JSON）
Future<void> saveSource({required String dbPath, required String sourceJson}) =>
    RustLib.instance.api
        .crateApiSaveSource(dbPath: dbPath, sourceJson: sourceJson);

/// 便捷函数：仅需 name + url 即可创建书源（自动填充 id/enabled/timestamps 等必填字段）
Future<String> createSource(
        {required String dbPath, required String name, required String url}) =>
    RustLib.instance.api
        .crateApiCreateSource(dbPath: dbPath, name: name, url: url);

/// 删除书源
Future<void> deleteSource({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteSource(dbPath: dbPath, id: id);

/// 批量删除书源 (ids_json 为 JSON 字符串数组)
Future<void> deleteSourcesBatch(
        {required String dbPath, required String idsJson}) =>
    RustLib.instance.api
        .crateApiDeleteSourcesBatch(dbPath: dbPath, idsJson: idsJson);

/// 启用 / 禁用书源
Future<void> setSourceEnabled(
        {required String dbPath, required String id, required bool enabled}) =>
    RustLib.instance.api
        .crateApiSetSourceEnabled(dbPath: dbPath, id: id, enabled: enabled);

/// 从 JSON 批量导入书源
Future<int> importSourcesFromJson(
        {required String dbPath, required String json}) =>
    RustLib.instance.api
        .crateApiImportSourcesFromJson(dbPath: dbPath, json: json);

/// 获取书源（core_source::types::BookSource 格式），用于下载
Future<String> getSourceForDownload(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetSourceForDownload(dbPath: dbPath, sourceId: sourceId);

/// 获取某本书的所有章节，返回 JSON 数组
Future<String> getBookChapters(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetBookChapters(dbPath: dbPath, bookId: bookId);

/// 更新章节内容
Future<void> updateChapterContent(
        {required String dbPath,
        required String chapterId,
        required String content}) =>
    RustLib.instance.api.crateApiUpdateChapterContent(
        dbPath: dbPath, chapterId: chapterId, content: content);

/// 保存章节（chapter_json 为 storage::Chapter 的 JSON）
Future<void> saveChapter(
        {required String dbPath, required String chapterJson}) =>
    RustLib.instance.api
        .crateApiSaveChapter(dbPath: dbPath, chapterJson: chapterJson);

/// 批量替换某本书的章节（chapters_json 为 storage::Chapter 数组 JSON），保留相同 URL 的已缓存正文
Future<void> replaceBookChaptersPreservingContent(
        {required String dbPath,
        required String bookId,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiReplaceBookChaptersPreservingContent(
        dbPath: dbPath, bookId: bookId, chaptersJson: chaptersJson);

/// 批量替换某本书的章节（chapters_json 为 storage::Chapter 数组 JSON），不保留旧章节正文
Future<void> replaceBookChapters(
        {required String dbPath,
        required String bookId,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiReplaceBookChapters(
        dbPath: dbPath, bookId: bookId, chaptersJson: chaptersJson);

/// 删除章节
Future<void> deleteChapter({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteChapter(dbPath: dbPath, id: id);

/// 保存阅读进度
Future<void> saveReadingProgress(
        {required String dbPath,
        required String bookId,
        required int chapterIndex,
        required int paragraphIndex,
        required int offset}) =>
    RustLib.instance.api.crateApiSaveReadingProgress(
        dbPath: dbPath,
        bookId: bookId,
        chapterIndex: chapterIndex,
        paragraphIndex: paragraphIndex,
        offset: offset);

/// 获取阅读进度，返回 JSON 或 null
Future<String> getReadingProgress(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetReadingProgress(dbPath: dbPath, bookId: bookId);

/// 获取某本书的所有书签，返回 JSON 数组
Future<String> getBookmarks({required String dbPath, required String bookId}) =>
    RustLib.instance.api.crateApiGetBookmarks(dbPath: dbPath, bookId: bookId);

/// 添加书签，返回新书签的 JSON
Future<String> addBookmark(
        {required String dbPath,
        required String bookId,
        required int chapterIndex,
        required int paragraphIndex,
        String? content}) =>
    RustLib.instance.api.crateApiAddBookmark(
        dbPath: dbPath,
        bookId: bookId,
        chapterIndex: chapterIndex,
        paragraphIndex: paragraphIndex,
        content: content);

/// 删除书签
Future<void> deleteBookmark(
        {required String dbPath, required String bookmarkId}) =>
    RustLib.instance.api
        .crateApiDeleteBookmark(dbPath: dbPath, bookmarkId: bookmarkId);

/// 搜索在线书籍（source_json 为 core_source::BookSource 的 JSON），返回搜索结果 JSON 数组
///
/// R82: 区分 ParserError::Empty（成功 0 结果，返回 `[]`）与其他失败（Network /
/// RuleConfig / Parse，作为 Err(String) 返回让 Dart 侧能 toast 出来）。
Future<String> searchBooksOnline(
        {required String sourceJson, required String keyword}) =>
    RustLib.instance.api
        .crateApiSearchBooksOnline(sourceJson: sourceJson, keyword: keyword);

/// 获取在线书籍详情，返回 JSON 或 null
Future<String> getBookInfoOnline(
        {required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiGetBookInfoOnline(sourceJson: sourceJson, bookUrl: bookUrl);

/// 获取在线章节列表，返回 JSON 数组
Future<String> getChapterListOnline(
        {required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiGetChapterListOnline(sourceJson: sourceJson, bookUrl: bookUrl);

/// 获取在线章节内容，返回 JSON 或 null
Future<String> getChapterContentOnline(
        {required String sourceJson, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentOnline(
        sourceJson: sourceJson, chapterUrl: chapterUrl);

/// 获取书源的原始 rule_search JSON（用于诊断），返回 JSON 或 null
Future<String> getSourceRuleSearchRaw(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetSourceRuleSearchRaw(dbPath: dbPath, sourceId: sourceId);

/// 从数据库加载书源并搜索（异步），返回搜索结果 JSON 数组
/// 包装结果：正常时返回 [{"ok":true,"data":[...]}]，失败时返回 [{"ok":false,"error":"..."}]
Future<String> searchWithSourceFromDbV2(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiSearchWithSourceFromDbV2(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

/// 从数据库加载书源并搜索（异步），返回搜索结果 JSON 数组
Future<String> searchWithSourceFromDb(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiSearchWithSourceFromDb(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

/// 从数据库加载书源并获取章节内容（异步），返回 JSON 或 null
Future<String> getChapterContentWithSourceFromDb(
        {required String dbPath,
        required String sourceId,
        required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentWithSourceFromDb(
        dbPath: dbPath, sourceId: sourceId, chapterUrl: chapterUrl);

/// 获取所有下载任务，返回 JSON 数组
Future<String> getDownloadTasks({required String dbPath}) =>
    RustLib.instance.api.crateApiGetDownloadTasks(dbPath: dbPath);

/// 根据书籍 ID 获取下载任务
Future<String> getDownloadTaskByBook(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetDownloadTaskByBook(dbPath: dbPath, bookId: bookId);

/// 创建下载任务（task_json 为 DownloadTask 的 JSON），返回 JSON
Future<String> createDownloadTask(
        {required String dbPath, required String taskJson}) =>
    RustLib.instance.api
        .crateApiCreateDownloadTask(dbPath: dbPath, taskJson: taskJson);

/// 事务性创建下载任务和章节
Future<String> createDownloadTaskWithChapters(
        {required String dbPath,
        required String taskJson,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiCreateDownloadTaskWithChapters(
        dbPath: dbPath, taskJson: taskJson, chaptersJson: chaptersJson);

/// 更新下载任务状态
Future<void> updateDownloadTaskStatus(
        {required String dbPath,
        required String taskId,
        required int status,
        String? errorMessage}) =>
    RustLib.instance.api.crateApiUpdateDownloadTaskStatus(
        dbPath: dbPath,
        taskId: taskId,
        status: status,
        errorMessage: errorMessage);

/// 更新下载进度
Future<void> updateDownloadProgress(
        {required String dbPath,
        required String taskId,
        required int downloadedChapters,
        required PlatformInt64 downloadedSize}) =>
    RustLib.instance.api.crateApiUpdateDownloadProgress(
        dbPath: dbPath,
        taskId: taskId,
        downloadedChapters: downloadedChapters,
        downloadedSize: downloadedSize);

/// 删除下载任务（同时清理已下载的文件）
Future<void> deleteDownloadTask(
        {required String dbPath, required String taskId}) =>
    RustLib.instance.api
        .crateApiDeleteDownloadTask(dbPath: dbPath, taskId: taskId);

/// 获取下载章节列表，返回 JSON 数组
Future<String> getDownloadChapters(
        {required String dbPath, required String taskId}) =>
    RustLib.instance.api
        .crateApiGetDownloadChapters(dbPath: dbPath, taskId: taskId);

/// 批量创建下载章节记录
Future<void> batchCreateDownloadChapters(
        {required String dbPath, required String chaptersJson}) =>
    RustLib.instance.api.crateApiBatchCreateDownloadChapters(
        dbPath: dbPath, chaptersJson: chaptersJson);

/// 更新下载章节状态
Future<void> updateDownloadChapterStatus(
        {required String dbPath,
        required String chapterId,
        required int status,
        String? filePath,
        required PlatformInt64 fileSize,
        String? errorMessage}) =>
    RustLib.instance.api.crateApiUpdateDownloadChapterStatus(
        dbPath: dbPath,
        chapterId: chapterId,
        status: status,
        filePath: filePath,
        fileSize: fileSize,
        errorMessage: errorMessage);

/// 下载并保存单个章节到本地文件，更新数据库状态
Future<String> downloadAndSaveChapter(
        {required String dbPath,
        required String taskId,
        required String downloadChapterId,
        required String sourceJson,
        required String chapterUrl,
        required String downloadDir}) =>
    RustLib.instance.api.crateApiDownloadAndSaveChapter(
        dbPath: dbPath,
        taskId: taskId,
        downloadChapterId: downloadChapterId,
        sourceJson: sourceJson,
        chapterUrl: chapterUrl,
        downloadDir: downloadDir);

/// 验证书源规则（source_json 为 core_source::types::BookSource 的 JSON），返回 JSON 数组
Future<String> validateSourceRules({required String sourceJson}) =>
    RustLib.instance.api.crateApiValidateSourceRules(sourceJson: sourceJson);

/// 验证数据库中的书源规则，返回 JSON 数组 [{field, severity, message}]
Future<String> validateSourceFromDb(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiValidateSourceFromDb(dbPath: dbPath, sourceId: sourceId);

/// 导出所有书源为 Legado 兼容 JSON 数组（camelCase 格式）
Future<String> exportAllSources({required String dbPath}) =>
    RustLib.instance.api.crateApiExportAllSources(dbPath: dbPath);

/// BATCH-27a: 导出书架为 JSON 数组（仅 name/author/intro 三字段，
/// 对齐原版 BookshelfViewModel.kt:102-128 exportBookshelf）。
/// 空书架返回 `"[]"`。
Future<String> exportBookshelfJson({required String dbPath}) =>
    RustLib.instance.api.crateApiExportBookshelfJson(dbPath: dbPath);

/// BATCH-27b: 刷新单本书的目录（"更新目录"批量任务的 leaf FRB）。
///
/// 流程：BookDao + SourceDao 拿数据 → parser.get_chapters 抓远端 toc →
/// 单事务写章节（保 content cache）+ 更新书 chapter_count / last_check_time。
/// 返回新章节数。
///
/// 错误：书 / 书源不存在、书源未配置 rule_toc、网络抓取失败等都返
/// `Future.error(String)`，调用方自行 catch 决定是否记 fail 计数。
/// 本地书（`source_id` 为空）应在 Dart 端 filter 掉，不会进到这里；
/// 真到这里也会返「缺少书源 ID」错。
Future<int> updateBookToc(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiUpdateBookToc(dbPath: dbPath, bookId: bookId);

/// BATCH-27c: 通用 webdav 列目录。`path` 相对 url，空串 = root。返
/// JSON 数组：`[{"name","isDir","size","lastModified"}, ...]`。与
/// [`webdavListBackups`] 区分 — 后者写死 backup 前缀过滤 + 返 String 列表。
Future<String> webdavListDir(
        {required String url,
        required String user,
        required String password,
        required String path}) =>
    RustLib.instance.api.crateApiWebdavListDir(
        url: url, user: user, password: password, path: path);

/// BATCH-27c: 通用 webdav 下载到本地路径，返写入字节数。
/// `targetLocalPath` 父目录由 caller 创建。
Future<PlatformInt64> webdavDownloadFile(
        {required String url,
        required String user,
        required String password,
        required String remotePath,
        required String targetLocalPath}) =>
    RustLib.instance.api.crateApiWebdavDownloadFile(
        url: url,
        user: user,
        password: password,
        remotePath: remotePath,
        targetLocalPath: targetLocalPath);

/// BATCH-27d: 切换书的「允许更新」状态（canUpdate）。canUpdate=false 后
/// 27b update_toc 批量目录刷新会跳过此本。
Future<void> setBookCanUpdate(
        {required String dbPath,
        required String id,
        required bool canUpdate}) =>
    RustLib.instance.api.crateApiSetBookCanUpdate(
        dbPath: dbPath, id: id, canUpdate: canUpdate);

// 注：清缓存复用 BATCH-26a 已有的 [`clearBookCache(dbPath, bookId)`]
// (funcId 80, line 688)，27d 不重新加 binding。

/// BATCH-27d: 删除书 + 可选删本地源文件。`deleteFile=true` 时对本地书
/// （book_url 'loc_book:<path>'）删 file（限定在 documentsDir 子树内）。
/// 不破坏 [`deleteBook`]（funcId 47）binary contract。
Future<void> deleteBookWithFile(
        {required String dbPath,
        required String id,
        required bool deleteFile,
        required String documentsDir}) =>
    RustLib.instance.api.crateApiDeleteBookWithFile(
        dbPath: dbPath,
        id: id,
        deleteFile: deleteFile,
        documentsDir: documentsDir);

/// BATCH-27e: 按书籍 URL 找匹配的启用书源。
///
/// 返回 `null` = 找不到 / 没启用书源 / URL 为空；非 null = 匹配书源
/// JSON 字符串（shape 与 `getAllSources` 单元素一致）。
Future<String?> findBookSourceForUrl(
        {required String dbPath, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiFindBookSourceForUrl(dbPath: dbPath, bookUrl: bookUrl);

/// 获取所有替换规则，返回 JSON 数组
Future<String> getReplaceRules({required String dbPath}) =>
    RustLib.instance.api.crateApiGetReplaceRules(dbPath: dbPath);

/// 保存替换规则（rule_json 为 storage::ReplaceRule 的 JSON），upsert 语义
Future<void> saveReplaceRule(
        {required String dbPath, required String ruleJson}) =>
    RustLib.instance.api
        .crateApiSaveReplaceRule(dbPath: dbPath, ruleJson: ruleJson);

/// 删除替换规则
Future<void> deleteReplaceRule({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteReplaceRule(dbPath: dbPath, id: id);

/// 启用 / 禁用替换规则
Future<void> setReplaceRuleEnabled(
        {required String dbPath, required String id, required bool enabled}) =>
    RustLib.instance.api.crateApiSetReplaceRuleEnabled(
        dbPath: dbPath, id: id, enabled: enabled);

/// 对内容应用所有已启用的替换规则。
///
/// 这是 P1-7 的修复：之前 Dart 端在每次切章节时通过 FRB 拉一次规则列表，
/// 然后在主 isolate 里循环 `RegExp(...).replaceAll`，长正文 + 多条规则会
/// 阻塞 UI。现在统一下沉到 Rust 单次调用：
///
///   - 编译失败的规则只 warn 一次（避免每章都 spam 日志）
///   - 整个循环在 Rust 端跑，不占 Dart 主 isolate
///   - 调用方只需把 db_path + 原始内容传过来
///
/// 同时 Dart 侧的 ReplaceRule 缓存也可以复用：参数加 `cache_generation`，
/// Rust 端用 OnceLock + RwLock 保存上次拉取的规则；调用方在 ReplaceRule
/// CRUD 后递增 generation 即可让缓存失效，不必每次走 DAO。
///
/// **R24**: scope 现在按 Legado 原版语义匹配。`book_name` 与
/// `book_origin` 由 caller 提供（reader_page 持有），filter 逻辑见
/// [`matches_scope`]。`apply_to_title=true` 表示本次跑作用于标题
/// 的规则；false 表示作用于正文。
Future<String> applyReplaceRules(
        {required String dbPath,
        required String content,
        required PlatformInt64 cacheGeneration,
        String? bookName,
        String? bookOrigin,
        required bool applyToTitle}) =>
    RustLib.instance.api.crateApiApplyReplaceRules(
        dbPath: dbPath,
        content: content,
        cacheGeneration: cacheGeneration,
        bookName: bookName,
        bookOrigin: bookOrigin,
        applyToTitle: applyToTitle);

// ============================================================
// 本地备份 / 恢复（批次 10）
// ============================================================

/// 把当前 DB 5 张表（books / book_groups / bookmarks / replace_rules /
/// book_sources）导出成 Legado 兼容的 zip 备份。
Future<void> exportBackupZip(
        {required String dbPath, required String outZipPath}) =>
    RustLib.instance.api
        .crateApiExportBackupZip(dbPath: dbPath, outZipPath: outZipPath);

/// 解压 zip → 字段映射 → upsert 入库。返回 `ImportSummary` 的 JSON 字符串
/// （`{books, groups, bookmarks, replace_rules, sources, errors}`）。
Future<String> importBackupZip(
        {required String dbPath, required String zipPath}) =>
    RustLib.instance.api
        .crateApiImportBackupZip(dbPath: dbPath, zipPath: zipPath);

/// 列 zip 内**已识别**的 Legado 备份文件名（不解析内容，dry-run 用）。
/// 返回 JSON 字符串数组。
Future<String> validateBackupZip({required String zipPath}) =>
    RustLib.instance.api.crateApiValidateBackupZip(zipPath: zipPath);

// ============================================================
// WebDAV 同步（批次 11）
// ============================================================

/// 探活 — 验证 WebDAV URL + 凭据。失败抛 String 错误。
Future<void> webdavCheck(
        {required String url,
        required String user,
        required String password}) =>
    RustLib.instance.api
        .crateApiWebdavCheck(url: url, user: user, password: password);

/// 列远端 base_url 下的 backup*.zip 文件名。返回 JSON 字符串数组。
Future<String> webdavListBackups(
        {required String url,
        required String user,
        required String password}) =>
    RustLib.instance.api
        .crateApiWebdavListBackups(url: url, user: user, password: password);

/// 本地 export → 临时 zip → PUT 到 WebDAV。
Future<void> webdavUploadBackup(
        {required String dbPath,
        required String url,
        required String user,
        required String password,
        required String fileName}) =>
    RustLib.instance.api.crateApiWebdavUploadBackup(
        dbPath: dbPath,
        url: url,
        user: user,
        password: password,
        fileName: fileName);

/// GET 远端 zip → 写到临时文件 → import → 返回 ImportSummary JSON。
Future<String> webdavDownloadBackup(
        {required String dbPath,
        required String url,
        required String user,
        required String password,
        required String fileName}) =>
    RustLib.instance.api.crateApiWebdavDownloadBackup(
        dbPath: dbPath,
        url: url,
        user: user,
        password: password,
        fileName: fileName);

/// 删除远端 backup zip。
Future<void> webdavDeleteBackup(
        {required String url,
        required String user,
        required String password,
        required String fileName}) =>
    RustLib.instance.api.crateApiWebdavDeleteBackup(
        url: url, user: user, password: password, fileName: fileName);

// ============================================================
// 备份密码持久化（批次 12 / 05-19）
// ============================================================

/// 设置备份密码（持久化到 `<documentsDir>/legado_local.json`）。
///
/// `password = ""` 等价于"未设密码"（与原 Legado `LocalConfig.password`
/// 默认值一致）。导出 zip 时仍走 AES 加密，但 key = MD5("")。
Future<void> setBackupPassword(
        {required String documentsDir, required String password}) =>
    RustLib.instance.api.crateApiSetBackupPassword(
        documentsDir: documentsDir, password: password);

/// 读取当前备份密码；不存在时返回空串。
Future<String> getBackupPassword({required String documentsDir}) =>
    RustLib.instance.api.crateApiGetBackupPassword(documentsDir: documentsDir);

// ============================================================
// 本地书导入（批次 13 / 05-19）
// ============================================================

/// 导入本地书（TXT / EPUB / UMD）。返回 `{"book_id": "..."}` JSON。
///
/// `file_path` 必须是 .txt / .epub / .umd 文件绝对路径；
/// `documents_dir` 用于复制源文件到 `<documents_dir>/local_books/`，
/// 防原文件后续被移动 / 删除导致 reader 打不开。
Future<String> importLocalBook(
        {required String dbPath,
        required String filePath,
        required String documentsDir}) =>
    RustLib.instance.api.crateApiImportLocalBook(
        dbPath: dbPath, filePath: filePath, documentsDir: documentsDir);

// ============================================================
// 阅读时长统计（批次 14 / 05-19）— ReadRecord
// ============================================================

/// 累加某本书的阅读时长（秒）。若 `book_id` 已存在则累加 + 更新
/// last_read_at；否则 INSERT 新行。reader_page 60s ticker 调用。
Future<void> addReadTime(
        {required String dbPath,
        required String bookId,
        required String bookName,
        required PlatformInt64 deltaSeconds}) =>
    RustLib.instance.api.crateApiAddReadTime(
        dbPath: dbPath,
        bookId: bookId,
        bookName: bookName,
        deltaSeconds: deltaSeconds);

/// 取单本书的阅读记录，返回 JSON `Option<ReadRecord>`（"null" 或对象）。
Future<String> getReadRecord(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetReadRecord(dbPath: dbPath, bookId: bookId);

/// 列出所有阅读记录（按 last_read_at DESC），返回 JSON 数组。
/// 设置页"阅读统计"用。
Future<String> listReadRecords({required String dbPath}) =>
    RustLib.instance.api.crateApiListReadRecords(dbPath: dbPath);

/// 全局总阅读时长（秒）。空表返回 0。
Future<PlatformInt64> getTotalReadTime({required String dbPath}) =>
    RustLib.instance.api.crateApiGetTotalReadTime(dbPath: dbPath);

// ============================================================
// 缓存管理（批次 15 / 05-19）— CacheStats
// ============================================================

/// 单本已缓存章节数。content 非 NULL 且非空串才算"已缓存"。
Future<PlatformInt64> countCachedChaptersForBook(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api.crateApiCountCachedChaptersForBook(
        dbPath: dbPath, bookId: bookId);

/// 列出所有书 + 已缓存章节数（按 cached DESC 排序）。
/// 返回 JSON 数组：`[{book_id, book_name, total_chapters, cached_chapters}]`。
Future<String> listBooksWithCacheStats({required String dbPath}) =>
    RustLib.instance.api.crateApiListBooksWithCacheStats(dbPath: dbPath);

/// 单本清空缓存：UPDATE chapters SET content=NULL WHERE book_id=?。
/// 返回受影响行数（与 chapter_count 一致）。
Future<PlatformInt64> clearBookCache(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api.crateApiClearBookCache(dbPath: dbPath, bookId: bookId);

/// 全局清空缓存：UPDATE chapters SET content=NULL（无 WHERE）。
/// 返回受影响行数。
Future<PlatformInt64> clearAllCache({required String dbPath}) =>
    RustLib.instance.api.crateApiClearAllCache(dbPath: dbPath);

// ============================================================
// RSS 源管理（批次 16 / 05-19）— RssSource
// ============================================================

/// 列出所有 RSS 源（按 custom_order ASC, source_name ASC），返回 JSON 数组。
Future<String> rssSourceListAll({required String dbPath}) =>
    RustLib.instance.api.crateApiRssSourceListAll(dbPath: dbPath);

/// 列出已启用的 RSS 源，返回 JSON 数组。
Future<String> rssSourceListEnabled({required String dbPath}) =>
    RustLib.instance.api.crateApiRssSourceListEnabled(dbPath: dbPath);

/// 列出指定分组下的 RSS 源（严格按 source_group = ? 匹配）。
Future<String> rssSourceListByGroup(
        {required String dbPath, required String group}) =>
    RustLib.instance.api
        .crateApiRssSourceListByGroup(dbPath: dbPath, group: group);

/// DISTINCT 分组列表（跳过 NULL/空），返回 JSON 字符串数组。
Future<String> rssSourceListGroups({required String dbPath}) =>
    RustLib.instance.api.crateApiRssSourceListGroups(dbPath: dbPath);

/// 按 source_url 取单条 RSS 源，返回 JSON `Option<RssSource>`。
Future<String> rssSourceGet({required String dbPath, required String url}) =>
    RustLib.instance.api.crateApiRssSourceGet(dbPath: dbPath, url: url);

/// upsert 单条 RSS 源（sourceJson = `RssSource` 的 JSON），返回受影响行数。
Future<PlatformInt64> rssSourceUpsert(
        {required String dbPath, required String sourceJson}) =>
    RustLib.instance.api
        .crateApiRssSourceUpsert(dbPath: dbPath, sourceJson: sourceJson);

/// 切换 enabled，返回受影响行数。
Future<PlatformInt64> rssSourceSetEnabled(
        {required String dbPath,
        required String url,
        required bool enabled}) =>
    RustLib.instance.api.crateApiRssSourceSetEnabled(
        dbPath: dbPath, url: url, enabled: enabled);

/// 按 source_url 删除 RSS 源，返回受影响行数。
Future<PlatformInt64> rssSourceDelete(
        {required String dbPath, required String url}) =>
    RustLib.instance.api.crateApiRssSourceDelete(dbPath: dbPath, url: url);

/// 批量导入 RSS 源（端口内部 / 原 Legado 双格式 JSON）。返回
/// `RssImportSummary` 的 JSON 字符串 (`{added, updated, skipped}`)。
Future<String> rssSourceImportJson(
        {required String dbPath, required String json}) =>
    RustLib.instance.api
        .crateApiRssSourceImportJson(dbPath: dbPath, json: json);

// ============================================================
// RSS 拉取 + 文章列表（批次 17 / 05-19）— RssArticle
// ============================================================

/// 拉取 RSS 源、解析、upsert 入库，返回 DB 排序后的文章列表 JSON。
///
/// - `sortName` / `sortUrl` 单 URL 模式可空字符串
/// - `page` MVP 仅取第 1 页（保留参数为批次 18 备用）
/// - 返回 JSON 数组：`[{origin, sort, title, pub_date, link, image,
///   description, variable, order_num, read_time, star}, ...]`
Future<String> rssGetArticles(
        {required String dbPath,
        required String sourceUrl,
        required String sortName,
        required String sortUrl,
        required int page}) =>
    RustLib.instance.api.crateApiRssGetArticles(
        dbPath: dbPath,
        sourceUrl: sourceUrl,
        sortName: sortName,
        sortUrl: sortUrl,
        page: page);

/// 列出 DB 已有的 RSS 文章（不拉取）。UI 切 sort tab 时用。
/// `sort = null/空` 表示不过滤分类。
Future<String> rssListArticles(
        {required String dbPath, required String sourceUrl, String? sort}) =>
    RustLib.instance.api.crateApiRssListArticles(
        dbPath: dbPath, sourceUrl: sourceUrl, sort: sort);

/// 按 (origin, link) 单条查询 RSS 文章，返回 JSON 或 "null"。
/// detail 页打开走这个，避免全数组遍历。
Future<String> rssArticleGetByOriginLink(
        {required String dbPath, required String origin, required String link}) =>
    RustLib.instance.api.crateApiRssArticleGetByOriginLink(
        dbPath: dbPath, origin: origin, link: link);

/// 标记文章已读（双写 rss_articles + rss_read_records），返回受影响行数。
Future<PlatformInt64> rssMarkRead(
        {required String dbPath,
        required String link,
        required PlatformInt64 ts}) =>
    RustLib.instance.api
        .crateApiRssMarkRead(dbPath: dbPath, link: link, ts: ts);

/// 某 RSS 源未读文章数。
Future<PlatformInt64> rssCountUnread(
        {required String dbPath, required String sourceUrl}) =>
    RustLib.instance.api
        .crateApiRssCountUnread(dbPath: dbPath, sourceUrl: sourceUrl);

/// 删除某 RSS 源下的全部文章（删源时清理）。
Future<PlatformInt64> rssDeleteArticlesBySource(
        {required String dbPath, required String sourceUrl}) =>
    RustLib.instance.api.crateApiRssDeleteArticlesBySource(
        dbPath: dbPath, sourceUrl: sourceUrl);

/// 解析 source.sort_url → `[{name, url}]` JSON。
/// 单 URL 模式 / 缺源 / 空字符串返回 `[]`。
Future<String> rssGetSortTabs(
        {required String dbPath, required String sourceUrl}) =>
    RustLib.instance.api
        .crateApiRssGetSortTabs(dbPath: dbPath, sourceUrl: sourceUrl);

// ============================================================
// RSS 文章详情 + 收藏（批次 18 / 05-19）— RssStar
// ============================================================

/// 拉取单篇 RSS 文章的完整正文 HTML。返回 JSON
/// `{"html": "...", "base_url": "..."}`。
///
/// - rule_content 非空 → 走规则路（reqwest GET → AnalyzeRule 抽）
/// - 否则 fallback 用 article.description 包装成 wrapper HTML
/// - 失败时透传 ParserError 描述（详情页应展示错误 + 重试按钮）
Future<String> rssFetchArticleContent(
        {required String dbPath,
        required String sourceUrl,
        required String link}) =>
    RustLib.instance.api.crateApiRssFetchArticleContent(
        dbPath: dbPath, sourceUrl: sourceUrl, link: link);

/// 收藏一篇 RSS 文章。`articleJson` 为 [`RssArticle`] 的 JSON 字符串
/// （detail 页可在 init 时通过 rss_list_articles 拿到完整对象后序列化）。
/// `sourceName` 来自 RssSource.source_name。
/// 重复收藏不会失败 — 走 INSERT OR REPLACE 把 star_time 刷新为最新。
Future<PlatformInt64> rssStarAdd(
        {required String dbPath,
        required String articleJson,
        required String sourceName}) =>
    RustLib.instance.api.crateApiRssStarAdd(
        dbPath: dbPath, articleJson: articleJson, sourceName: sourceName);

/// 取消收藏。返回受影响行数（0 表示原本就没收藏，依旧不报错）。
Future<PlatformInt64> rssStarRemove(
        {required String dbPath,
        required String origin,
        required String link}) =>
    RustLib.instance.api.crateApiRssStarRemove(
        dbPath: dbPath, origin: origin, link: link);

/// 是否已收藏。
Future<bool> rssStarIsStarred(
        {required String dbPath,
        required String origin,
        required String link}) =>
    RustLib.instance.api.crateApiRssStarIsStarred(
        dbPath: dbPath, origin: origin, link: link);

/// 列出收藏（按 star_time DESC）。`limit < 0` 表示无分页。
/// 返回 `Vec<RssStar>` 的 JSON 数组。
Future<String> rssStarList(
        {required String dbPath,
        required PlatformInt64 limit,
        required PlatformInt64 offset}) =>
    RustLib.instance.api.crateApiRssStarList(
        dbPath: dbPath, limit: limit, offset: offset);

// ============================================================
// 订阅源 RuleSub MVP（批次 19 / 05-19）
// ============================================================

/// 列出所有订阅源（custom_order ASC, name ASC），返回 JSON 数组。
Future<String> ruleSubListAll({required String dbPath}) =>
    RustLib.instance.api.crateApiRuleSubListAll(dbPath: dbPath);

/// 新建订阅源 — Rust 端自动生成 UUID + 时间戳。返回新 RuleSub JSON。
/// `subType`：0=书源 / 1=RSS / 2=替换规则。
Future<String> ruleSubCreate(
        {required String dbPath,
        required String name,
        required String url,
        required int subType}) =>
    RustLib.instance.api.crateApiRuleSubCreate(
        dbPath: dbPath, name: name, url: url, subType: subType);

/// 更新已有订阅源（id 必须存在），返回受影响行数。
Future<PlatformInt64> ruleSubUpdate(
        {required String dbPath,
        required String id,
        required String name,
        required String url,
        required int subType}) =>
    RustLib.instance.api.crateApiRuleSubUpdate(
        dbPath: dbPath, id: id, name: name, url: url, subType: subType);

/// 删除订阅源，返回受影响行数（0 表示原本就不存在）。
Future<PlatformInt64> ruleSubDelete(
        {required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiRuleSubDelete(dbPath: dbPath, id: id);

/// 单条订阅源刷新（async）— 拉远端 JSON 并按 sub_type 路由 import。
/// 返回 JSON：`{"sub_type":N, "count":N | "summary":{...} | "error":"..."}`。
Future<String> ruleSubRefresh({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiRuleSubRefresh(dbPath: dbPath, id: id);

/// 全部订阅源刷新（async）— 单条失败不打断其它，返回 JSON 数组：
/// `[{"id":..., "name":..., "sub_type":N, "ok":bool, "message":"..."}]`。
Future<String> ruleSubRefreshAll({required String dbPath}) =>
    RustLib.instance.api.crateApiRuleSubRefreshAll(dbPath: dbPath);

/// 按 id 取单条订阅源，返回 JSON `Option<RuleSub>`（不存在为 `null`）。
Future<String> ruleSubGet({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiRuleSubGet(dbPath: dbPath, id: id);

// ============================================================
// 书源实跑 LiveTest（批次 21 / 05-19）
// ============================================================

/// 实跑 4 路 live test：search → book_info → toc → content。返回
/// [`LiveTestReport`] 的 JSON 字符串：
/// `{"stages": [{"stage", "ok", "latency_ms", "sample?", "error?"}, ...],
///   "static_issues": [{"field", "severity", "message"}, ...]}`
///
/// `keyword` 由 UI 输入；建议默认 `"测试"` 或 `"test"`。任一阶段失败
/// 不短路，4 个 stages 一定都会出现，失败的 stage 用 `error` 字段标明
/// 原因（[`ParserError::Display`] 字符串）。
Future<String> validateSourceLive(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiValidateSourceLive(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

// ============================================================
// 批量书源校验 (批次 check-sources / PR2, funcId 119)
// ============================================================

/// 批量校验多个书源。`sourceIds` 是 String 列表的 JSON 字符串（如 `["id1","id2"]`），
/// `configJson` 是 [`CheckConfig`] 的 JSON 字符串。返回 JSON 数组
/// `Vec<SourceCheckProgress>`，最后一个元素 `is_done = true`。
///
/// 每个源跑完会同时写回 book_sources 表的 respond_time / last_check_error /
/// last_check_at 字段。并发数 / 超时 / stage 过滤由 config_json 控制。
Future<String> batchCheckSources(
        {required String dbPath,
        required String sourceIdsJson,
        required String configJson}) =>
    RustLib.instance.api.crateApiBatchCheckSources(
        dbPath: dbPath,
        sourceIdsJson: sourceIdsJson,
        configJson: configJson);
